server:
  port: 8000

spring:
  application:
    name: ApiGateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: authentication-service
          uri: lb://AUTHENTICATION
          predicates:
            - Path=/api/auth/**
        - id: user-management-service
          uri: lb://USERMANAGEMENT
          predicates:
            - Path=/api/users/**
        - id: carMnangement-service
          uri: lb://CARMANAGEMENT
          predicates:
            - Path=/api/cars/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
