server:
  port: 8000

spring:
  application:
    name: ApiGateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        # Public authentication routes (no filter)
        - id: authentication-service
          uri: lb://AUTHENTICATION
          predicates:
            - Path=/api/auth/**
        
        # Ban/Unban operations - superAdmin only
        - id: user-ban-operations
          uri: lb://USERMANAGEMENT
          predicates:
            - Path=/api/users/**
          filters:
            - name: RoleAuthorizationFilter


        # Car management - requires authentication (any authenticated user)
        - id: carMnangement-service
          uri: lb://CARSMANAGEMENT
          predicates:
            - Path=/api/cars/**
          filters:
            - RoleAuthorizationFilter

        # Offers - General (Authenticated users)
        - id: offers-general
          uri: lb://OFFERSMANAGEMENT
          predicates:
            - Path=/api/offers/**
          filters:
            - RoleAuthorizationFilter





eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
